### ISSUE TITLE
可否不用geoIp来定位ip

### ISSUE THREAD

**Issue by shangxinbo** [m31271n/jet#2]
我在用shadowsocks 的pac原则来分发请求，我看jet在用geoIp来分发请求，请问如果我去掉geoIp分发会不会有问题

**Comment by ghost** [comment]
去掉 GeoIP 后，Jet 就是纯粹的 SOCKS 转 HTTP 的代理了。

如果，你已经使用了 PAC 来分发请求，并且需要一个 HTTP 代理，这样做是可以的。

如果不需要 HTTP 代理，Jet 就不是必需的了。
