### ISSUE TITLE
想问一下为什么要分http和https

### ISSUE THREAD

**Issue by shangxinbo** [m31271n/jet#3]
httpAgent 和 httpsAgent需要做什么区分，出于什么考虑要单拿出来https做个angent呢？

**Comment by ghost** [comment]
> 因为 Node HTTP 服务器的 request 事件和 connect 事件的事件处理器参数不一致。

在 Node 中，对于 `http.createServer()` 创建出的服务器：
+ 普通的 HTTP 请求会触发 request 事件
+ HTTPS 请求会触发 connect 事件

这两个事件的事件处理器的参数：
+ request:
  + request <http.IncomingMessage>
  + response <http.ServerResponse>
+ connect:
  + request <http.IncomingMessage> Arguments for the HTTP request, as it is in the 'request' event
  + socket <net.Socket> Network socket between the server and client
  + head <Buffer> The first packet of the tunneling stream (may be empty)

可以看出，两个事件处理的参数并不一致。

* * *

综上，HTTP 请求触发 request 事件，HTTPS 请求触发 connect 事件。由于事件处理器的参数不一致，它们需要使用不同的 Agent。

即使将 httpAgent 和 httpsAgent 合并成一个方法，为了解决事件处理器参数不一致的问题，仍然需要在这个方法中对事件类型进行判断，这样倒是不简单明了了。

**Comment by ghost** [comment]
@shangxinbo 如果解决了你的疑问，可以直接关闭这个 issue。如果有更好的解决方案，欢迎 PR。
